name: jost_pay_wallet
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  clipboard: ^0.1.3
  fluttertoast: ^8.2.2
  custom_pin_screen: ^0.5.0
  pin_code_fields: ^8.0.1
  flutter_staggered_grid_view: ^0.7.0
  dotted_decoration: ^2.0.0
  flutter_switch: ^0.3.2
  mobile_scanner: ^3.5.0
  http: ^1.1.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  flutter_windowmanager: ^0.2.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  device_info_plus: ^9.1.0
  mobile_device_identifier: ^0.0.2

  #Shared plus
  share_plus: ^7.2.1

  # finger print
  local_auth: ^2.1.6
  cached_network_image: ^3.3.0
  socket_io_client: ^2.0.3+1
  intl: ^0.18.1
  url_launcher: ^6.2.1
  declarative_refresh_indicator: ^0.1.0
  qr_flutter: ^4.1.0
  web3dart: ^2.7.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/dashboard/


  fonts:
    - family: NimbusSanLBol
      fonts:
        - asset: assets/fonts/NimbusSanL-Bol.otf

    - family: NimbusSanLBolIta
      fonts:
        - asset: assets/fonts/NimbusSanL-BolIta.otf

    - family: NimbusSanLRegular
      fonts:
        - asset: assets/fonts/NimbusSanL-Reg.otf

    - family: NimbusSanLRegularItalic
      fonts:
        - asset: assets/fonts/NimbusSanL-RegIta.otf
